version: '3.8'

services:
  mysqldb:
    image: "mysql:8.0"
    container_name: mysqldb
    restart: always
    ports:
      - 3306:3306
    networks:
      - myapp-network
    environment:
      MYSQL_DATABASE: shorted-link
      MYSQL_USER: root
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_root_password
      - db_password
    volumes:
      - datavolume:/var/lib/mysql
volumes:
  datavolume:
    name: data-volume

secrets:
  db_password:
    file: db_password
  db_root_password:
    file: db_root_password

networks:
  myapp-network:
    name: shorted-network
