version: '3.3'

services:
  shorted-be:
    build: limits-service/
    container_name: shorted-be
    networks:
      - myapp-network
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: "-XX:+UnlockExperimentalVMOptions -XX:-UseG1GC -XX:+UseZGC"
      spring.datasource.url : "jdbc:mysql://mysqldb:3306/shorted-link?allowPublicKeyRetrieval=true"
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - myapp-network
    environment:
      MYSQL_DATABASE: shorted-link
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - mysql-data:/var/lib/mysql

  shorted-fe:
    build: shorted-fe/
    container_name: shorted-fe
    ports:
      - "3000:3000"
    links:
      - shorted-be

networks:
  myapp-network:

volumes:
  mysql-data: