version: '3.8'

services:
  mysqldb:
    image: "mysql:8.0"
    container_name: mysqldb
    restart: always
    ports:
      - 3306:3306
    networks:
      - myapp-network
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./my_init_script.sql:/docker-entrypoint-initdb.d/init.sql
      - datavolume:/var/lib/mysql
volumes:
  datavolume:
    name: data-volume

networks:
  myapp-network:
    name: shorted-network
